# Generated by Django 4.2 on 2023-04-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_remove_quote_customer_quote_address_quote_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=250, null=True),
        ),
    ]
