# Generated by Django 4.2 on 2023-04-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='stat',
            field=models.CharField(choices=[('PD', 'Pending'), ('RV', 'Reviewing'), ('AP', 'Approved')], default='PD', max_length=20),
        ),
    ]
