# Generated by Django 4.2 on 2023-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_quote_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='stat',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
