# Generated by Django 4.2 on 2023-04-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_alter_quote_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='jobfile',
            field=models.FileField(blank=True, null=True, upload_to='jobfiles/'),
        ),
    ]
