# Generated by Django 4.2 on 2023-04-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_quote_jobfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
