# Generated by Django 4.2 on 2023-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_quote_name_alter_quote_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
