# Generated by Django 4.2 on 2023-04-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_alter_quote_name_alter_quote_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
