# Generated by Django 4.2 on 2023-04-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_alter_quote_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Home'),
        ),
    ]
