# Generated by Django 4.2 on 2023-04-15 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0014_alter_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
