# Generated by Django 4.2 on 2023-04-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0015_alter_quote_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='user_name',
            new_name='requester',
        ),
    ]
