# Generated by Django 4.2 on 2023-05-02 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0017_alter_quote_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='requester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
