# Generated by Django 4.2 on 2023-05-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='otherdetails',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
