# Generated by Django 4.2 on 2023-05-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leftimage',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rightimage',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
