# Generated by Django 4.2 on 2023-05-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_otherdetails_project_additionalright_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additionalright',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bottomdetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
