# Generated by Django 4.2 on 2023-05-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='leftimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rightimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
