# Generated by Django 4.2 on 2023-05-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_leftimage_alter_project_rightimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
