# Generated by Django 4.2 on 2023-05-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_header_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='link',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
