# Generated by Django 4.2 on 2023-05-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_header_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
