# Generated by Django 4.2 on 2023-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['start', 'end']},
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['start'], name='resume_work_start_96f4f7_idx'),
        ),
    ]
