# Generated by Django 4.2 on 2023-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifications',
            options={'ordering': ['start', '-end']},
        ),
        migrations.AddIndex(
            model_name='certifications',
            index=models.Index(fields=['start'], name='resume_cert_start_04a133_idx'),
        ),
    ]
