# Generated by Django 4.2 on 2023-05-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_certifications_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start',
            field=models.DateField(),
        ),
    ]
