# Generated by Django 4.2 on 2023-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['start', '-end']},
        ),
        migrations.RemoveIndex(
            model_name='workexperience',
            name='resume_work_start_566c28_idx',
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['start'], name='resume_work_start_96f4f7_idx'),
        ),
    ]
