# Generated by Django 4.2 on 2023-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_workexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='name',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
