# Generated by Django 4.2 on 2023-05-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_workexperience_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='name',
        ),
    ]
