# Generated by Django 4.2 on 2023-05-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_rename_name_education_school_education_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start', '-end']},
        ),
        migrations.RemoveIndex(
            model_name='education',
            name='resume_educ_start_ce07f2_idx',
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['-start'], name='resume_educ_start_792c7a_idx'),
        ),
    ]
