# Generated by Django 4.2 on 2023-05-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-start', 'end']},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start', 'end']},
        ),
    ]
